name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start containers
      run: |
        docker-compose up -d --build

    - name: Wait for services to be ready
      run: |
        sleep 10  # Give time for MariaDB to initialize
        docker-compose ps

    - name: Run tests
      run: |
        docker-compose exec -T app npm test

    - name: Stop containers
      if: always()
      run: docker-compose down

    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ github.repository }}:latest
          ${{ github.repository }}:${{ github.sha }} 