name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Validate lockfile for back
      - name: Check lockfile (back)
        working-directory: ./back
        run: |
          npm install


      - name: Install dependencies (back)
        working-directory: ./back
        run: npm i

      - name: Build (back)
        working-directory: ./back
        run: npm run build --if-present

      - name: Test (back)
        working-directory: ./back
        run: npm test

      # Validate lockfile for front
      - name: Check lockfile (front)
        working-directory: ./front
        run: |
          npm install

      - name: Install dependencies (front)
        working-directory: ./front
        run: npm i
        continue-on-error: true

      - name: Build (front)
        working-directory: ./front
        run: npm run build --if-present
        continue-on-error: true 
